// import {styles} from './RequestForms/FormStyle'
selectionColor = 'black'
focusedUnderlineColor = '#00bcd4'
blurUnderlineColor = '#9b9b9b'

export const requestParameters = {
    visitor: [

        {
            'fieldName': 'name',
            'placeholder': 'Visitor Names',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'purpose',
            'placeholder': 'Purpose Of Visit',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Reference Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Reference Employee Email ID',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Visitor Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },
    ],
    vendor: [

        {
            'fieldName': 'name',
            'placeholder': 'Vendor Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'vendorOrg',
            'placeholder': 'Vendor Orginisation Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Visitor Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    newJoinee: [

        {
            'fieldName': 'name',
            'placeholder': 'Name of joinee',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': false,
        },
        {
            'fieldName': 'candidateId',
            'placeholder': 'Candidate ID of joinee',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Reporting Manager name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Reporting Manager EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Candidate Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    forgotId: [

        {
            'fieldName': 'name',
            'placeholder': 'Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': false,
        },
        {
            'fieldName': 'employeeId',
            'placeholder': 'Employee ID',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Project Manager Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Project Manager EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': (new Date()).toLocaleDateString(),
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'defaultValue': (new Date()).toLocaleDateString(),
            'editable': false,
            'keyboardType': 'none',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Employee alternate Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    vip: [
        {
            'fieldName': 'name',
            'placeholder': 'Visitor Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'purpose',
            'placeholder': 'Purpose Of Visit',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Visitor Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    family: [

        {
            'fieldName': 'name',
            'placeholder': 'Name of family member',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'relation',
            'placeholder': 'Relation with employee',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Visitor Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    conferenceAttendee: [
        {
            'fieldName': 'name',
            'placeholder': 'Attendee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'purpose',
            'placeholder': 'Purpose Of Visit (Confrence Topic)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Visitor Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    client: [

        {
            'fieldName': 'name',
            'placeholder': 'Client Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'clientOrg',
            'placeholder': 'Client Orginisation',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Client Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    interviewee: [
        {
            'fieldName': 'name',
            'placeholder': 'Interviewee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': false,
        },
        {
            'fieldName': 'purpose',
            'placeholder': 'Interview for position of',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'POC Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'POC EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Date of Interview dd-mm-yy',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Interviewee Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ],
    guest: [
        {
            'fieldName': 'name',
            'placeholder': 'Guest Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
            'multipalNamesAllowed': true,
        },
        {
            'fieldName': 'purpose',
            'placeholder': 'Purpose Of Visit',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeName',
            'placeholder': 'Refrence Employee Name',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'default',
        },
        {
            'fieldName': 'refEmployeeEmail',
            'placeholder': 'Refrence Employee EmailId',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'email-address',
        },
        {
            'fieldName': 'visitDate',
            'placeholder': 'Expected date of visit MM/DD/YY',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        }, {
            'fieldName': 'idProof',
            'placeholder': 'Visitor ID Proof (Aadhar Number)',
            'selectionColor': selectionColor,
            'focusedUnderlineColor': focusedUnderlineColor,
            'blurUnderlineColor': blurUnderlineColor,
            'keyboardType': 'numeric',
        },
        {'fieldName':'visitorEmail',
            'placeholder':'Guest Email ID',
            'selectionColor':selectionColor,
            'focusedUnderlineColor':focusedUnderlineColor,
            'blurUnderlineColor':blurUnderlineColor,
            'keyboardType':'email-address', 
        },    
    ]
}