// import {styles} from './RequestForms/FormStyle'
selectionColor = 'black'
focusedUnderlineColor = '#6d9ada'
blurUnderlineColor = '#9b9b9b'

export const requestParameters = {
visitor:[
    {'fieldName':'name',
        'placeholder':'Visitor Names',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'purpose',
        'placeholder':'Purpose Of Visits',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Reference Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Reference Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of Visit DD-MM-YY',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],
vendor:[

    {'fieldName':'name',
        'placeholder':'Vendor Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'vendorOrg',
        'placeholder':'Orginisation Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],
newJoinee:[

    {'fieldName':'name',
        'placeholder':'Visitor Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'candidateId',
        'placeholder':'Purpose Of Visit',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],	
forgotId:[

    {'fieldName':'name',
        'placeholder':'Visitor Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'employeeId',
        'placeholder':'Employee ID',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'number', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Manager Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Manager EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],	
vip:[

    {'fieldName':'name',
        'placeholder':'Visitor Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'purpose',
        'placeholder':'Purpose Of Visit',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],
family:[

    {'fieldName':'name',
        'placeholder':'Visitor Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'relation',
        'placeholder':'Relation with employee',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],
conferenceAttendee:[
    {'fieldName':'name',
        'placeholder':'Attendee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'purpose',
        'placeholder':'Purpose Of Visit',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],	
client:[

    {'fieldName':'name',
        'placeholder':'Client Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'clientOrg',
        'placeholder':'Client Orginisation',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],	
interviewee:[
    {'fieldName':'name',
        'placeholder':'Interviewee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'purpose',
        'placeholder':'Interview for position of',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'POC Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'POC EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of Interview dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
],
guest:[
    {'fieldName':'name',
        'placeholder':'Guest Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'purpose',
        'placeholder':'Purpose Of Visit',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeName',
        'placeholder':'Refrence Employee Name',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'default', 
    },
    {'fieldName':'refEmployeeEmail',
        'placeholder':'Refrence Employee EmailId',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'email-address', 
    },
    {'fieldName':'visitDate',
        'placeholder':'Date of visit dd-mm-yy',
        'selectionColor':selectionColor,
        'focusedUnderlineColor':focusedUnderlineColor,
        'blurUnderlineColor':blurUnderlineColor,
        'keyboardType':'numeric', 
    },    
]
}